name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  test-linux:
    name: test-linux
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  test-macos:
    name: test-macos
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  test-windows:
    name: test-windows
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install OpenSSL
        run: pacman -S mingw-w64-x86_64-openssl
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
